// TODO: CREATE APP ROUTES ENUM

// TODO: CREATE THE DETAILS SCREEN PARAMS TYPE

// TODO: CREATE THE TROOT STACK PARAMS TYPE

// TODO:CREATE THE STACK NAVIGATOR

// TODO: CREATE A GENERIC THAT EXTENDS ROOT STACK PARAMS
//       FOR APP NAVIGATION PROPS

// TODO: CREATE A GENERIC FOR APP ROUTE PROPS
